### ISSUE TITLE
Attachments only display when editing page

### ISSUE THREAD

**Issue by atlarep** [michael-dev/dokuwikimediaattachment#1]
I like the functionality of attaching files to a specific documents with a few clicks. However, I can only see the attachments while in the editor and not while reading the page (even as admin). 
Any ideas of what needs to be changed?

**Comment by michael-dev** [comment]
That is what this plugin is supposed to do.

README says
"This plugin adds an attachment (media) listing/upload/link-insertion/delete area below the text editor."

You can use the dokuwiki medialist plugin (https://github.com/michael-dev/dokuwikipluginmedialist/) for listing attachments in read-mode.
